In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
import seaborn as sb

%matplotlib inline
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('ggplot')
 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
train_values = pd.read_csv( 'train_values.csv', index_col='building_id')
train_labels = pd.read_csv( 'train_labels.csv', index_col='building_id')
cleaned_train_labels = pd.read_csv( 'cleaned_train.csv')

In [3]:
cleaned_train_labels.describe()

building_id   damage_grade  geo_level_1_id  geo_level_2_id  \
count  2.606010e+05  260601.000000   260601.000000   260601.000000   
mean   5.256755e+05       2.238272       13.900353      701.074685   
std    3.045450e+05       0.611814        8.033617      412.710734   
min    4.000000e+00       1.000000        0.000000        0.000000   
25%    2.611900e+05       2.000000        7.000000      350.000000   
50%    5.257570e+05       2.000000       12.000000      702.000000   
75%    7.897620e+05       3.000000       21.000000     1050.000000   
max    1.052934e+06       3.000000       30.000000     1427.000000   

       geo_level_3_id  count_floors_pre_eq            age  area_percentage  \
count   260601.000000        260601.000000  260601.000000    260601.000000   
mean      6257.876148             2.129723      26.535029         8.018051   
std       3646.369645             0.727665      73.565937         4.392231   
min          0.000000             1.000000       0.000000         1.000000   
25%       3073.000000             2.000000      10.000000         5.000000   
50%       6270.000000             2.000000      15.000000         7.000000   
75%       9412.000000             2.000000      30.000000         9.000000   
max      12567.000000             9.000000     995.000000       100.000000   

       height_percentage  count_families  
count      260601.000000   260601.000000  
mean            5.434365        0.983949  
std             1.918418        0.418389  
min             2.000000        0.000000  
25%             4.000000        1.000000  
50%             5.000000        1.000000  
75%             6.000000        1.000000  
max            32.000000        9.000000

In [14]:
X = cleaned_train_labels[['geo_level_1_id','geo_level_2_id', 'geo_level_3_id']].values
y = cleaned_train_labels['damage_grade'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
n_neighbors = 20
 
knn = KNeighborsClassifier(n_neighbors)
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 0.72
Accuracy of K-NN classifier on test set: 0.71


In [16]:
#Precision
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[ 2197  3662   387]
 [ 1429 31348  4191]
 [  276  9163 12498]]
              precision    recall  f1-score   support

           1       0.56      0.35      0.43      6246
           2       0.71      0.85      0.77     36968
           3       0.73      0.57      0.64     21937

    accuracy                           0.71     65151
   macro avg       0.67      0.59      0.62     65151
weighted avg       0.70      0.71      0.70     65151



In [18]:
pred

array([2, 2, 2, ..., 1, 1, 2], dtype=int64)